name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the application directory, or clone the repository if it doesn't exist
          if [ ! -d "/home/${{ secrets.EC2_USER }}/fruit-app" ]; then
            git clone https://github.com/GeorgeOkarskyi/fruit-jar.git /home/${{ secrets.EC2_USER }}/fruit-app
          fi
          cd /home/${{ secrets.EC2_USER }}/fruit-app

          # Pull the latest changes from the main branch
          git checkout main
          git pull origin main

          # Create or update the .env file
          echo "VITE_GET_FRUITS_API_URL=${{ secrets.VITE_GET_FRUITS_API_URL }}" > .env
          echo "GET_FRUITS_API_URL=${{ secrets.GET_FRUITS_API_URL }}" >> ./server/.env
          echo "PORT=${{ secrets.GET_FRUITS_API_PORT }}" >> ./server/.env

          # Install ui dependencies
          npm install

          # Buid ui
          npm run build

          # Check if nginx is installed; if not, install it
          if ! [ -x "$(command -v nginx)" ]; then
            echo "Nginx not found. Installing Nginx..."
            sudo apt update -y
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
          else
            echo "Nginx is already installed."
          fi

          sudo cp -r /home/${{ secrets.EC2_USER }}/fruit-app/dist/* /var/www/html/    

          # Start the application using PM2 or nohup so it runs in the background and doesn't block the SSH session
          if ! [ -x "$(command -v pm2)" ]; then
            sudo npm install pm2 -g
          fi

          # Start or restart the application with PM2 (background process manager)
          pm2 restart "fruit-app" --name "fruit-app" -- run start:server

          sudo systemctl restart nginx
        EOF
